# Generated by Django 5.2.10 on 2026-01-16 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='bcc_email',
            field=models.EmailField(blank=True, help_text='BCC email address (receives a copy of EVERY email)', max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='cc_email',
            field=models.EmailField(blank=True, help_text='CC email address (receives a copy of EVERY email)', max_length=254, null=True),
        ),
    ]
